# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aa653efbf43f20af4701a8d5643bf7d65c58862149ab69052b2c2bab97b5029387f87a5d48bedafdd3bad8cd8e46ebdb4cf46c4ba5be7b12ce4fd82178e6265

test:
  secret_key_base: 6e7cde11e4e55382b9d0ae26884648c7015b858bffbc05b31e2ced1a7cdcaf9207e51164de9f5f76b24bb015a149f8cea83eefa9b2863e92677c9f456bec05e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
